### ISSUE TITLE
carrierwave-qiniu configuration error

### ISSUE THREAD

**Issue by LaoLiulaoliu** [huobazi/carrierwave-qiniu#17]
```
.../config/initializers/carrierwave.rb:8:in `block in <top (required)>': undefined method `qiniu_bucket_private=' for CarrierWave::Uploader::Base:Class (NoMethodError)

    from /Users/bishop/.rvm/gems/ruby-2.1.4/gems/carrierwave-0.10.0/lib/carrierwave/uploader/configuration.rb:118:in `configure'
    from /Users/bishop/.rvm/gems/ruby-2.1.4/gems/carrierwave-0.10.0/lib/carrierwave.rb:14:in `configure'
    from /Users/bishop/project/medical/ourdrs/config/initializers/carrierwave.rb:2:in `<top (required)>'
    from /Users/bishop/.rvm/gems/ruby-2.1.4/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:241:in `load'
```

配置我照抄：
config/initializers/carrierwave.rb

```
CarrierWave.configure do |config|
  config.storage             = :qiniu
  config.qiniu_access_key    = "your qiniu access_key"
  config.qiniu_secret_key    = 'your qiniu secret_key'
  config.qiniu_bucket        = "carrierwave-qiniu-example"
  config.qiniu_bucket_domain = "carrierwave-qiniu-example.aspxboy.com"
  config.qiniu_bucket_private= true #default is false
  config.qiniu_block_size    = 4*1024*1024
  config.qiniu_protocol      = "http"
end
```

Gemfile:

```
gem 'carrierwave'
gem 'carrierwave-qiniu'
gem 'qiniu-rs'
```

**Comment by Lupeipei** [comment]
我这边遇到的同样的问题，看前辈们的讨论，我试着把gem 'qiniu-rs'删除了，可是部署的时候，终端报错，显示Bundler::GemRequireError: There was an error while trying to load the gem 'carrierwave-qiniu'， Gem Load Error is: You dot't have the 'qiniu-rs' gem installed。

**Comment by huobazi** [comment]
@Lupeipei 你用的版本太老额

```
gem 'carrierwave-qiniu', '~> 1.1.5'
```
