### ISSUE TITLE
 cannot load such file -- qiniu (LoadError)

### ISSUE THREAD

**Issue by 42thcoder** [huobazi/carrierwave-qiniu#32]
```
/Users/hackerZhang/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.1.5/lib/active_support/dependencies.rb:247:in `require': cannot load such file -- qiniu (LoadError)
	from /Users/hackerZhang/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.1.5/lib/active_support/dependencies.rb:247:in `block in require'
	from /Users/hackerZhang/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.1.5/lib/active_support/dependencies.rb:232:in `load_dependency'
	from /Users/hackerZhang/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.1.5/lib/active_support/dependencies.rb:247:in `require'
	from /Users/hackerZhang/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/carrierwave-qiniu-41f765a0f42f/lib/carrierwave/storage/qiniu.rb:3:in `<top (required)>'
	from /Users/hackerZhang/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.1.5/lib/active_support/dependencies.rb:247:in `require'
	from /Users/hackerZhang/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.1.5/lib/active_support/dependencies.rb:247:in `block in require'
	from /Users/hackerZhang/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.1.5/lib/active_support/dependencies.rb:232:in `load_dependency'
	from /Users/hackerZhang/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.1.5/lib/active_support/dependencies.rb:247:in `require'
	from /Users/hackerZhang/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/carrierwave-qiniu-41f765a0f42f/lib/carrierwave-qiniu.rb:2:in `<top (required)>'
	from /Users/hackerZhang/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.7.10/lib/bundler/runtime.rb:76:in `require'
	from /Users/hackerZhang/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.7.10/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
	from /Users/hackerZhang/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.7.10/lib/bundler/runtime.rb:72:in `each'
	from /Users/hackerZhang/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.7.10/lib/bundler/runtime.rb:72:in `block in require'
	from /Users/hackerZhang/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.7.10/lib/bundler/runtime.rb:61:in `each'
	from /Users/hackerZhang/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.7.10/lib/bundler/runtime.rb:61:in `require'
	from /Users/hackerZhang/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.7.10/lib/bundler.rb:134:in `require'
	from /Users/hackerZhang/work/weddingServer/config/application.rb:7:in `<top (required)>'
	from /Users/hackerZhang/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.1.5/lib/rails/commands/commands_tasks.rb:79:in `require'
	from /Users/hackerZhang/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.1.5/lib/rails/commands/commands_tasks.rb:79:in `block in server'
	from /Users/hackerZhang/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.1.5/lib/rails/commands/commands_tasks.rb:76:in `tap'
	from /Users/hackerZhang/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.1.5/lib/rails/commands/commands_tasks.rb:76:in `server'
	from /Users/hackerZhang/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.1.5/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	from /Users/hackerZhang/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.1.5/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

GEM

```
# 七牛服务
gem 'qiniu', github: 'qiniu/ruby-sdk'
gem 'carrierwave'
gem 'carrierwave-qiniu', github: 'huobazi/carrierwave-qiniu'
```

@huobazi

**Comment by 42thcoder** [comment]
应该是七牛的问题. @longbai

**Comment by longbai** [comment]
@42thcoder 收到，我来看下
