### ISSUE TITLE
升级0.1.8.1版本以后报错

### ISSUE THREAD

**Issue by watsy0007** [huobazi/carrierwave-qiniu#40]
错误信息如下

```
Error:[rake --tasks] rake aborted!
NameError: uninitialized constant CarrierWave::Storage::Qiniu::Connection::Carrierwave
/Users/watsy/.rvm/gems/ruby-2.2.0/gems/carrierwave-qiniu-0.1.8.1/lib/carrierwave/storage/qiniu.rb:77:in `<class:Connection>'
/Users/watsy/.rvm/gems/ruby-2.2.0/gems/carrierwave-qiniu-0.1.8.1/lib/carrierwave/storage/qiniu.rb:10:in `<class:Qiniu>'
/Users/watsy/.rvm/gems/ruby-2.2.0/gems/carrierwave-qiniu-0.1.8.1/lib/carrierwave/storage/qiniu.rb:8:in `<module:Storage>'
/Users/watsy/.rvm/gems/ruby-2.2.0/gems/carrierwave-qiniu-0.1.8.1/lib/carrierwave/storage/qiniu.rb:7:in `<module:CarrierWave>'
/Users/watsy/.rvm/gems/ruby-2.2.0/gems/carrierwave-qiniu-0.1.8.1/lib/carrierwave/storage/qiniu.rb:6:in `<top (required)>'
/Users/watsy/.rvm/gems/ruby-2.2.0/gems/carrierwave-qiniu-0.1.8.1/lib/carrierwave-qiniu.rb:2:in `<top (required)>'
/Users/watsy/.rvm/gems/ruby-2.2.0/gems/bundler-1.10.4/lib/bundler/runtime.rb:76:in `require'
/Users/watsy/.rvm/gems/ruby-2.2.0/gems/bundler-1.10.4/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
/Users/watsy/.rvm/gems/ruby-2.2.0/gems/bundler-1.10.4/lib/bundler/runtime.rb:72:in `each'
/Users/watsy/.rvm/gems/ruby-2.2.0/gems/bundler-1.10.4/lib/bundler/runtime.rb:72:in `block in require'
/Users/watsy/.rvm/gems/ruby-2.2.0/gems/bundler-1.10.4/lib/bundler/runtime.rb:61:in `each'
/Users/watsy/.rvm/gems/ruby-2.2.0/gems/bundler-1.10.4/lib/bundler/runtime.rb:61:in `require'
/Users/watsy/.rvm/gems/ruby-2.2.0/gems/bundler-1.10.4/lib/bundler.rb:134:in `require'
/Users/watsy/Documents/code/ruby/huaxing/unicornext/unicornext/config/application.rb:10:in `<top (required)>'
/Users/watsy/Documents/code/ruby/huaxing/unicornext/unicornext/Rakefile:4:in `require'
/Users/watsy/Documents/code/ruby/huaxing/unicornext/unicornext/Rakefile:4:in `<top (required)>'
/Users/watsy/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/rake_module.rb:28:in `load'
/Users/watsy/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/rake_module.rb:28:in `load_rakefile'
/Users/watsy/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/application.rb:689:in `raw_load_rakefile'
/Users/watsy/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/application.rb:94:in `block in load_rakefile'
/Users/watsy/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/Users/watsy/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/application.rb:93:in `load_rakefile'
/Users/watsy/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/application.rb:77:in `block in run'
/Users/watsy/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/Users/watsy/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/application.rb:75:in `run'
/Users/watsy/Documents/code/ruby/huaxing/unicornext/unicornext/bin/rake:8:in `<main>'
```

gemfile.lock中信息如下

```
carrierwave (0.10.0)
      activemodel (>= 3.2.0)
      activesupport (>= 3.2.0)
      json (>= 1.7)
      mime-types (>= 1.16)
    carrierwave-qiniu (0.1.8.1)
      carrierwave
      qiniu (~> 6.4.2)
```

**Comment by huobazi** [comment]
ref https://github.com/huobazi/carrierwave-qiniu/pull/42
