### ISSUE TITLE
CarrierWave::Qiniu::Style:Module报错

### ISSUE THREAD

**Issue by zmcNotafraid** [huobazi/carrierwave-qiniu#71]
```
Bundler::GemRequireError: There was an error while trying to load the gem 'carrierwave-qiniu'.
Gem Load Error is: undefined method `class_methods' for CarrierWave::Qiniu::Style:Module
Backtrace for gem load error is:
/Users/zmcNotafraid/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/carrierwave-qiniu-1.0.0/lib/carrierwave/qiniu/style.rb:8:in `<module:Style>'
/Users/zmcNotafraid/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/carrierwave-qiniu-1.0.0/lib/carrierwave/qiniu/style.rb:5:in `<module:Qiniu>'
/Users/zmcNotafraid/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/carrierwave-qiniu-1.0.0/lib/carrierwave/qiniu/style.rb:4:in `<module:CarrierWave>'
```
正常配置的，运行出现以上问题，carrierwave-qiniu 1.0.0 版本 ruby 2.2.0 rails 4.0.12

**Comment by huobazi** [comment]
@zmcNotafraid  the ``` class_methods ``` was introduced in [Rails 4.2](http://apidock.com/rails/ActiveSupport/Concern/class_methods). 

ref: https://github.com/rails/rails/commit/b16c36e688970df2f96f793a759365b248b582ad

**Comment by bastengao** [comment]
@huobazi 我晚上提个 PR

**Comment by huobazi** [comment]
@zmcNotafraid  请使用 [V1.0.1](https://rubygems.org/gems/carrierwave-qiniu/versions/1.0.1)

@bastengao 感谢您的帮助！

**Comment by zmcNotafraid** [comment]
好的 感谢！
